language: python
python:
  - "2.6"
  - "2.7"
env:
  global:
    - secure: "NY9tMAk0TCgAn7PhjAu+JUcc2kMG3Html/HREMd2Y6CAGXz4BfpyqTJ70xh5uUJhwrOXYf3YZSmuXmkKkpDp8ap2xdD+kkywD6XA7EtdCTLxmAUoZHNasvEcrSYZFB5h+LS4XDB4Klw1pWHAb1NZWXH9/fpEedUBmOhElvqnNSs="
    - secure: "fSI6kbNwo3p/It8Ed9p7iyoFSIwwAKDnhUi/w9tHlPQ90OhhExGqtqqWFl53DtIR5WIFybO+rSA4tKufQXZIzg6rnQez8XPjn472cDq56w56y1hI+G8RG10AlHogzLMtBro3AxrX+AlWwzDaM7ECg9NluJ0b0AOuUNfEboOYoOQ="

install:
  - pip install selenium nose --use-mirrors

before_script:
  - curl https://gist.github.com/santiycr/5139581/raw/python_appengine_setup.py | python
  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash

script:
  - nosetests --processes=5 --process-timeout=600 -v tests
